# -*- coding: utf-8 -*-
"""InsyaAllah_fiks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hKVaiWGYa3kmuDZ4BKD5pC5e_zBaVMlz
"""

!pip install -q transformers scikit-learn seaborn matplotlib

import pandas as pd
import numpy as np
import torch
import re
import random

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
from sklearn.utils.class_weight import compute_class_weight

import matplotlib.pyplot as plt
import seaborn as sns

from transformers import AutoTokenizer, AutoModelForSequenceClassification, get_linear_schedule_with_warmup
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
import torch.nn.functional as F

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv(
    '/content/drive/MyDrive/myproject/TurnBackHoax_fiks.csv',
    encoding='latin1', sep=';', engine='python', on_bad_lines='skip'
)

df['text'] = df['judul'].fillna('') + " " + df['konten'].fillna('') + " " + df['ringkasan'].fillna('')

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    if len(text.split()) < 5:
        return ""
    return text

df['text'] = df['text'].apply(clean_text)
df = df[df['text'] != ""]

# ambil beberapa contoh acak
sample_df = df.sample(5, random_state=42)

def raw_text(row):
    return (str(row['judul']) + " " + str(row['konten']) + " " + str(row['ringkasan']))

comparison = []

for _, row in sample_df.iterrows():
    before = raw_text(row)
    after = clean_text(before)
    comparison.append({
        "Sebelum": before[:200],
        "Sesudah": after[:200]
    })

comparison_df = pd.DataFrame(comparison)
print(comparison_df)

plt.figure(figsize=(12, 6))
sns.countplot(y='label', data=df, order=df['label'].value_counts().index)
plt.title('Distribution of Labels in the Dataset')
plt.xlabel('Count')
plt.ylabel('Label')
plt.show()

def augment(text):
    words = text.split()
    if len(words) > 6:
        i = random.randint(0, len(words)-2)
        words[i], words[i+1] = words[i+1], words[i]
    return " ".join(words)

df_aug = df.copy()
df_aug['text'] = df_aug['text'].apply(augment)

df = pd.concat([df, df_aug]).reset_index(drop=True)

le = LabelEncoder()
df['label_enc'] = le.fit_transform(df['label'])

train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['text'],
    df['label_enc'],
    test_size=0.2,
    stratify=df['label_enc'],
    random_state=42
)

print(df[['label', 'label_enc']].drop_duplicates().sort_values('label_enc'))

for i, label in enumerate(le.classes_):
    print(f"{i} → {label}")

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_labels),
    y=train_labels
)

class_weights = torch.tensor(class_weights, dtype=torch.float)

class FocalLoss(torch.nn.Module):
    def __init__(self, alpha=None, gamma=2):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, logits, targets):
        ce_loss = F.cross_entropy(logits, targets, reduction='none')
        pt = torch.exp(-ce_loss)

        if self.alpha is not None:
            at = self.alpha[targets]
            loss = at * (1 - pt) ** self.gamma * ce_loss
        else:
            loss = (1 - pt) ** self.gamma * ce_loss

        return loss.mean()

class TextDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=512):
        self.texts = texts.reset_index(drop=True)
        self.labels = labels.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx],
            truncation=True,
            padding='max_length',
            max_length=self.max_len,
            return_tensors='pt'
        )
        return {
            'input_ids': enc['input_ids'].squeeze(),
            'attention_mask': enc['attention_mask'].squeeze(),
            'labels': torch.tensor(self.labels[idx])
        }

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def train_eval(model_name):
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=len(le.classes_)
    ).to(device)

    for param in model.base_model.embeddings.parameters():
        param.requires_grad = False

    train_dataset = TextDataset(train_texts, train_labels, tokenizer)
    val_dataset = TextDataset(val_texts, val_labels, tokenizer)

    train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=16)

    optimizer = AdamW(model.parameters(), lr=2e-5)

    loss_fn = FocalLoss(alpha=class_weights.to(device), gamma=2)

    for epoch in range(5):
        model.train()
        total_loss = 0

        for batch in train_loader:
            optimizer.zero_grad()

            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            loss = loss_fn(outputs.logits, labels)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

            optimizer.step()
            total_loss += loss.item()

        print(model_name, "Epoch", epoch+1, "Loss:", total_loss)

    model.eval()
    preds, true_labels = [], []

    with torch.no_grad():
        for batch in val_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits

            pred = torch.argmax(logits, dim=1).cpu().numpy()
            preds.extend(pred)
            true_labels.extend(batch['labels'].numpy())

    acc = accuracy_score(true_labels, preds)
    f1 = f1_score(true_labels, preds, average='weighted')

    return acc, f1, preds, true_labels

indobert_acc, indobert_f1, indobert_preds, true_labels = train_eval("indobenchmark/indobert-base-p1")
mbert_acc, mbert_f1, mbert_preds, _ = train_eval("bert-base-multilingual-cased")

print("IndoBERT:", indobert_acc, indobert_f1)
print("mBERT:", mbert_acc, mbert_f1)

ensemble = []

for p1, p2 in zip(indobert_preds, mbert_preds):
    if p1 == p2:
        ensemble.append(p1)
    else:
        ensemble.append(p1)

ensemble = np.array(ensemble)

ens_acc = accuracy_score(true_labels, ensemble)
ens_f1 = f1_score(true_labels, ensemble, average='weighted')

print("Ensemble:", ens_acc, ens_f1)

def plot_cm(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure()
    sns.heatmap(cm, annot=True, fmt='d')
    plt.title(title)
    plt.show()

plot_cm(true_labels, indobert_preds, "IndoBERT")
plot_cm(true_labels, mbert_preds, "mBERT")
plot_cm(true_labels, ensemble, "Ensemble")

models = ["IndoBERT", "mBERT", "Ensemble"]
accuracy = [indobert_acc, mbert_acc, ens_acc]
f1 = [indobert_f1, mbert_f1, ens_f1]

plt.figure()
plt.bar(models, accuracy)
plt.title("Accuracy Comparison")
plt.show()

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def evaluate_metrics(y_true, y_pred):
    acc  = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, average='weighted', zero_division=0)
    rec  = recall_score(y_true, y_pred, average='weighted', zero_division=0)
    f1   = f1_score(y_true, y_pred, average='weighted')

    return acc, prec, rec, f1

indobert_acc, indobert_prec, indobert_rec, indobert_f1 = evaluate_metrics(true_labels, indobert_preds)

mbert_acc, mbert_prec, mbert_rec, mbert_f1 = evaluate_metrics(true_labels, mbert_preds)

ens_acc, ens_prec, ens_rec, ens_f1 = evaluate_metrics(true_labels, ensemble)

results_df = pd.DataFrame({
    "Model": ["IndoBERT", "mBERT", "Ensemble"],
    "Accuracy": [indobert_acc, mbert_acc, ens_acc],
    "Precision": [indobert_prec, mbert_prec, ens_prec],
    "Recall": [indobert_rec, mbert_rec, ens_rec],
    "F1 Score": [indobert_f1, mbert_f1, ens_f1]
})

print(results_df)

models = ["IndoBERT", "mBERT", "Ensemble"]

plt.figure()
plt.bar(models, [indobert_acc, mbert_acc, ens_acc])
plt.title("Accuracy Comparison")
plt.show()

plt.figure()
plt.bar(models, [indobert_f1, mbert_f1, ens_f1])
plt.title("F1 Score Comparison")
plt.show()

for i in range(5):
    print("Teks :", val_texts.iloc[i][:100])
    print("Label asli :", le.inverse_transform([true_labels[i]])[0])
    print("Prediksi   :", le.inverse_transform([indobert_preds[i]])[0])
    print("-"*50)

import pandas as pd

sample_results = pd.DataFrame({
    "Text": val_texts[:10].values,
    "True": le.inverse_transform(true_labels[:10]),
    "Pred": le.inverse_transform(indobert_preds[:10])
})

print(sample_results)